# Generated by Django 4.0 on 2022-04-19 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DH11Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='My Office Desk', max_length=20, null=True)),
                ('time_of_record', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 15, 53, 55, 527125))),
            ],
        ),
    ]
