# Generated by Django 4.0 on 2022-04-19 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dh11sensor',
            name='time_of_record',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 16, 3, 37, 965833)),
        ),
    ]
