# Generated by Django 4.0 on 2022-05-26 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_tracker', '0002_alter_dh11sensor_time_of_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dh11sensor',
            name='time_of_record',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
